### ISSUE TITLE
Better error messages for users with pipes in their usernames

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#325]
```
OKAPI caught the following exception while executing API method request.
This is an error in OUR code and should be fixed. Please contact the
developer of the module that threw this error. Thanks!

===== ERROR MESSAGE =====
Undefined index: --|Aine|--
=========================

--- Stack trace ---
#0 
/var/www/www.opencaching.de/code/htdocs/okapi/services/users/by_username.php(37)
: okapi\OkapiErrorHandler::handle(8, 'Undefined index...', 
'/var/www/www.op...', 37, Array)
#1 [internal function]: 
okapi\services\users\by_username\WebService::call(Object(okapi\OkapiHttpRequest)
)
#2 /var/www/www.opencaching.de/code/htdocs/okapi/service_runner.php(134): 
call_user_func(Array, Object(okapi\OkapiHttpRequest))
#3 /var/www/www.opencaching.de/code/htdocs/okapi/views/method_call.php(28): 
okapi\OkapiServiceRunner::call('services/users/...', 
Object(okapi\OkapiHttpRequest))
#4 [internal function]: okapi\views\method_call\View::call('services/users/...')
#5 /var/www/www.opencaching.de/code/htdocs/okapi/controller.php(77): 
call_user_func_array(Array, Array)
#6 /var/www/www.opencaching.de/code/htdocs/okapi/controller.php(98): 
okapi\OkapiScriptEntryPointController::dispatch_request('/okapi/services...')
#7 {main}

--- OKAPI method called ---
/okapi/services/users/by_username
?fields=uuid
&langpref=de%7Cen
...
&username=--%7CAine%7C--

--- OKAPI revision ---
938

```

Original issue reported on code.google.com by `rygielski` on 10 Nov 2014 at 6:44

**Comment by following5** [comment]
see issue #339
