### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [opencaching/okapi#330]
```
"""
OKAPI caught the following exception while executing API method request.
This is an error in OUR code and should be fixed. Please contact the
developer of the module that threw this error. Thanks!

===== ERROR MESSAGE =====
Trying to get property of non-object
=========================

--- Stack trace ---
#0 /serve/www/oc_ro/oc_www/okapi/services/apisrv/installations.php(77): 
okapi\OkapiErrorHandler::handle(8, 'Trying to get p...', '/serve/www/oc_r...', 
77, Array)
#1 [internal function]: 
okapi\services\apisrv\installations\WebService::call(Object(okapi\OkapiInternalR
equest))
#2 /serve/www/oc_ro/oc_www/okapi/service_runner.php(136): call_user_func(Array, 
Object(okapi\OkapiInternalRequest))
#3 /serve/www/oc_ro/oc_www/okapi/views/menu.inc.php(70): 
okapi\OkapiServiceRunner::call('services/apisrv...', 
Object(okapi\OkapiInternalRequest))
#4 /serve/www/oc_ro/oc_www/okapi/views/method_doc.php(38): 
okapi\views\menu\OkapiMenu::get_installations()
#5 [internal function]: okapi\views\method_doc\View::call('services/caches...')
#6 /serve/www/oc_ro/oc_www/okapi/controller.php(77): 
call_user_func_array(Array, Array)
#7 /serve/www/oc_ro/oc_www/okapi/controller.php(98): 
okapi\OkapiScriptEntryPointController::dispatch_request('/okapi/services...')
#8 {main}

--- OKAPI method called ---
/okapi/services/caches/mark.html

--- OKAPI revision ---
1055

--- Request headers ---
Host: www.opencaching.ro
Connection: close
User-Agent: Mozilla/5.0 (compatible; Baiduspider/2.0; 
+http://www.baidu.com/search/spider.html)
Accept-Language: en-US
Accept-Encoding: gzip
Accept: */*
"""
```

Original issue reported on code.google.com by `rygielski` on 7 Jan 2015 at 12:15

**Comment by wrygiel** [comment]
Fixed in c86e63436b7318407763b3bd2ee56a572d887eef
