### ISSUE TITLE
"Table was not locked with LOCK TABLES" problem after MySQL upgrade

### ISSUE THREAD

**Issue by wrygiel** [opencaching/okapi#424]
When run on MySQL 5.7.12:

<pre>
===== ERROR MESSAGE =====
SQLSTATE[HY000]: General error: 1100 Table 'okapi_cache' was not locked with LOCK TABLES
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/core.php(552): PDO->query('\n            se...')
#1 /srv/ocpl/okapi/core.php(2184): okapi\Db::query('\n            se...')
#2 /srv/ocpl/okapi/core.php(1135): okapi\Cache::get('mail_admins_cou...')
#3 /srv/ocpl/okapi/cronjobs.php(97): okapi\Okapi::mail_admins('Cronjob error: ...', '===== ERROR MES...')
#4 /srv/ocpl/okapi/core.php(1386): okapi\cronjobs\CronJobController::run_jobs('pre-request')
#5 /srv/ocpl/okapi/core.php(1501): okapi\Okapi::execute_prerequest_cronjobs()
#6 /srv/ocpl/okapi/controller.php(61): okapi\Okapi::init_internals(true)
#7 /srv/ocpl/okapi/controller.php(98): okapi\OkapiScriptEntryPointController::dispatch_request('')
#8 {main}
</pre>

My guess is that this stacktrace points to just one of many affected places.

**Comment by wrygiel** [comment]
Might be related to this issue: https://bugs.mysql.com/bug.php?id=72887

**Comment by wrygiel** [comment]
Reverted. It seems that OCPL is currently running a PHP version which doesn't recognize the `finally` statement.

**Comment by wrygiel** [comment]
Wrong solution, again...
