### ISSUE TITLE
Duplicate key when inserting personal cache notes

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#530]
We are getting errors like this from opencaching.pl for about a week now:

```
===== ERROR MESSAGE =====
okapi\core\Exception\DbException:
SQL Error 1062: Duplicate entry '55923-73729' for key 'PRIMARY'

The query was:

                    insert into cache_notes (
                        cache_id, user_id, date, desc_html, `desc`
                    ) values (
                        '55923',
                        '73729',
                        NOW(), 0,
                        'N 51Â° 56.022\' E 015Â° 27.654\''
                    )
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/core/Db.php(266): okapi\core\Db::throwProperDbException(Object(PDOException), '\n              ...')
#1 /srv/ocpl/okapi/services/caches/save_personal_notes/WebService.php(172): okapi\core\Db::query('\n              ...')
#2 /srv/ocpl/okapi/services/caches/save_personal_notes/WebService.php(75): okapi\services\caches\save_personal_notes\WebService::update_notes(55923, 73729, 'N 51\xC2\xB0 56.022' ...')
#3 [internal function]: okapi\services\caches\save_personal_notes\WebService::call(Object(okapi\core\Request\OkapiHttpRequest))
#4 /srv/ocpl/okapi/core/OkapiServiceRunner.php(139): call_user_func(Array, Object(okapi\core\Request\OkapiHttpRequest))
#5 /srv/ocpl/okapi/views/method_call/View.php(19): okapi\core\OkapiServiceRunner::call('services/caches...', Object(okapi\core\Request\OkapiHttpRequest))
#6 [internal function]: okapi\views\method_call\View::call('services/caches...')
#7 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(51): call_user_func_array(Array, Array)
#8 /srv/ocpl/okapi/index.php(50): okapi\OkapiScriptEntryPointController::dispatch_request('services/caches...')
#9 {main}

--- OKAPI method called ---
/okapi/services/caches/save_personal_notes
?cache_code=OP8M8H
&langpref=pl%7Cen
&new_value=N%2051%C2%B0%2056.022%27%20E%20015%C2%B0%2027.654%27
&oauth_consumer_key=p9QkYcFzV7bWZemtJ5FT
&oauth_nonce=16e6a3fcf73aa42b21160174fac21eb
&oauth_signature_method=HMAC-SHA1
&oauth_timestamp=1520695558
&oauth_token=fX2BWGQjNxn2vxT9aYd5
&oauth_version=1.0
&old_value=N%2051%C2%B0%2056.024%27%20E%20015%C2%B0%2027.657%27
&oauth_signature=H%2Bq4i3%2BMyguxnAu1lhBHkO%2BqO2I%3D

--- OKAPI version ---
1687 (a18bee1a2c15f4bea9015ee9648ff8e46adff809)
```

Either the table index is broken, or it is a race condition because someone calls this method with the same input in high frequency. I will implement an untested try-and-error protection against race condtions (currently don't have a running OCPL develsite).

**Comment by following5** [comment]
But will implement an equivalent change for OCDE and test that.

**Comment by following5** [comment]
> But will implement an equivalent change for OCDE and test that.

OCDE has other indexes. Okay then, untested fix for OCPL.
