### ISSUE TITLE
Incompatibility with new PL database configuration

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#540]
Opencaching.pl has switched to a strict SQL type checking. Some errors to be fixed:

```
PHP Fatal error:
Uncaught okapi\\core\\Exception\\DbException: SQL Error 1292: Truncated incorrect DOUBLE value: ''

The query was:

insert into okapi_search_results (set_id, cache_id)
 select distinct
 '91857'
 caches.cache_id
 from
 caches

 where (caches.wp_oc is not null) and ((true)) and ((caches.status in ('1','2'))) and ((caches.cache_id not in ('')))

 in /srv/ocpl/okapi/core/Db.php:217\nStack trace:\n#0 /srv/ocpl/okapi/core/Db.php(201): okapi\\core\\Db::throwProperDbException(Object(PDOException), '\\n ...')
#1 /srv/ocpl/okapi/services/caches/search/save/WebService.php(142): okapi\\core\\Db::execute('\\n ...')
#2 /srv/ocpl/okapi/services/caches/search/save/WebService.php(85): okapi\\services\\caches\\search\\save\\WebService::get_set(Array, Array, Array,...\n', referer: https://opencaching.pl/CacheMap/embeded
```

[Edit: I manually expanded \n in the SQL statement above when copying it here; may have acidentially deleted the comma after '91857'.]

CronJob Error: okapi\core\CronJob\ChangeLogWriterJob
```
===== ERROR MESSAGE =====
ErrorException:
Undefined offset: 0
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/services/caches/geocaches/WebService.php(527): okapi\core\OkapiErrorHandler::handle(8, 'Undefined offse...', '/srv/ocpl/okapi...', 527, Array)
#1 [internal function]: okapi\services\caches\geocaches\WebService::call(Object(okapi\core\Request\OkapiInternalRequest))
#2 /srv/ocpl/okapi/core/OkapiServiceRunner.php(139): call_user_func(Array, Object(okapi\core\Request\OkapiInternalRequest))
#3 /srv/ocpl/okapi/services/replicate/ReplicateCommon.php(298): okapi\core\OkapiServiceRunner::call('services/caches...', Object(okapi\core\Request\OkapiInternalRequest))
#4 /srv/ocpl/okapi/services/replicate/ReplicateCommon.php(101): okapi\services\replicate\ReplicateCommon::generate_changelog_entries('services/caches...', 'geocache', 'cache_codes', 'code', Array, 'code|names|loca...', false, true, NULL)
#5 /srv/ocpl/okapi/core/CronJob/ChangeLogWriterJob.php(15): okapi\services\replicate\ReplicateCommon::update_clog_table()
#6 /srv/ocpl/okapi/core/CronJob/CronJobController.php(79): okapi\core\CronJob\ChangeLogWriterJob->execute()
#7 /srv/ocpl/okapi/core/Okapi.php(449): okapi\core\CronJob\CronJobController::run_jobs('cron-5')
#8 /srv/ocpl/okapi/views/cron5/View.php(25): okapi\core\Okapi::execute_cron5_cronjobs()
#9 [internal function]: okapi\views\cron5\View::call()
#10 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(51): call_user_func_array(Array, Array)
#11 /srv/ocpl/okapi/index.php(50): okapi\OkapiScriptEntryPointController::dispatch_request('cron5')
#12 {main}

--- OKAPI method called ---
/okapi/cron5

--- OKAPI version ---
1715 (d950aaedd12a6ddebd7380e62a23dbace6242ddf)
```

**Comment by following5** [comment]
```
===== ERROR MESSAGE =====
ErrorException:
Undefined offset: 0
=========================

--- Stack trace ---
#0 /srv/ocpl/okapi/services/caches/geocaches/WebService.php(527):
okapi\core\OkapiErrorHandler::handle(8, 'Undefined offse...', '/srv/ocpl/okapi...', 527,
Array)
#1 [internal function]:
okapi\services\caches\geocaches\WebService::call(Object(okapi\core\Request\OkapiInternalRequest
))
#2 /srv/ocpl/okapi/core/OkapiServiceRunner.php(139): call_user_func(Array,
Object(okapi\core\Request\OkapiInternalRequest))
#3 /srv/ocpl/okapi/services/caches/geocache/WebService.php(59):
okapi\core\OkapiServiceRunner::call('services/caches...',
Object(okapi\core\Request\OkapiInternalRequest))
#4 [internal function]:
okapi\services\caches\geocache\WebService::call(Object(okapi\core\Request\OkapiHttpRequest))
#5 /srv/ocpl/okapi/core/OkapiServiceRunner.php(139): call_user_func(Array,
Object(okapi\core\Request\OkapiHttpRequest))
#6 /srv/ocpl/okapi/views/method_call/View.php(19):
okapi\core\OkapiServiceRunner::call('services/caches...',
Object(okapi\core\Request\OkapiHttpRequest))
#7 [internal function]: okapi\views\method_call\View::call('services/caches...')
#8 /srv/ocpl/okapi/OkapiScriptEntryPointController.php(51): call_user_func_array(Array,
Array)
#9 /srv/ocpl/okapi/index.php(50):
okapi\OkapiScriptEntryPointController::dispatch_request('services/caches...')
#10 {main}

--- OKAPI method called ---
/okapi/services/caches/geocache
?cache_code=OP8UPQ
&fields=code|name|location|type|status|difficulty|terrain|size|size2|date_hidden|trackables_cou
nt|owner|founds|notfounds|rating|rating_votes|recommendations|description|hint|images|latest_lo
gs|alt_wpts|attrnames|req_passwd|trackables|gc_code|attribution_note|attr_acodes|willattends|sh
ort_description
&attribution_append=none
&lpc=all
&log_fields=uuid|date|user|type|comment|images
&langpref=pl|en
&consumer_key=....

--- OKAPI version ---
1715 (d950aaedd12a6ddebd7380e62a23dbace6242ddf)
```
Looks like mixing of strings and number types in `where cache_id in (...)` does not work, and some broken cache row with ID 0 is returned.

**Comment by following5** [comment]
However, the same query with another cache (OP8UZF) works fine. OP8UPQ exists but is not publicly visible on the OC.pl site. The OC.pl website links it by cache ID 64048.

**Comment by following5** [comment]
@deg-pl 
Can you try this on OC.pl database:

`select * from caches where cache_id in ('')`

Should return an empty set, but the above error messages suggest that it returns a row with cache_id 0. Then, deleting that row should fix the problem.

**Comment by kojoty** [comment]
> @deg-pl
> Can you try this on OC.pl database:
> 
> `select * from caches where cache_id in ('')`
> 
> Should return an empty set, but the above error messages suggest that it returns a row with cache_id 0. Then, deleting that row should fix the problem.

@following5 
```
MariaDB [ocpldb]> select * from caches where cache_id in ('');
Empty set (0.002 sec)
```
but from yesterday afternoon ocpl run with disabled strict mode - we have too many errors and we need to first cleanup it offline

currently running modes are:
`sql_mode  = ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION `

**Comment by following5** [comment]
Ok, thanks. Dou you have a copy of the first error email above (_Truncated incorrect DOUBLE value: ''_)? I manually expanded the newlines when copying it here and may have accidentally deleted a comma. Then deleted the email ...

**Comment by following5** [comment]
> but from yesterday afternoon ocpl run with disabled strict mode

Would need the output in strict mode to track down the error ...

**Comment by kojoty** [comment]
@following5 small clue for this issue:
I've made small investigation and it seems we had:
- 5 records for cache_id=0 in cache_attribs
- 1 record with cache_id=0 in cache_desc

I don't know much about the first case cause these records could be there for ages but 
cache_desc record was from the day of our DB migration - I suppose that this is not a random event...

...and of course 
`SELECT * FROM `cache_desc` where cache_id IN ('')`
returns that record with cache_id = 0

I think we can close this issue...

**Comment by following5** [comment]
Alright. I thought it was the `caches` table, bit it's `cache_desc`.
