### ISSUE TITLE
PHP 7.2 incompatibility

### ISSUE THREAD

**Issue by deg-pl** [opencaching/okapi#550]
From Apache error.log:
```
[Fri Nov 02 19:58:33.489866 2018] [proxy_fcgi:error] [pid 1344:tid 140579459688192] [client 78.154.8
5.165:55877] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Pa
rameter must be an array or an object that implements Countable in /srv/ocpl/okapi/services/caches/f
ormatters/garmin/WebService.php:107\nStack trace:\n#0 [internal function]: okapi\\core\\OkapiErrorHa
ndler::handle(2, 'count(): Parame...', '/srv/ocpl/okapi...', 107, Array)\n#1 /srv/ocpl/okapi/service
s/caches/formatters/garmin/WebService.php(107): count(NULL)\n#2 [internal function]: okapi\\services
\\caches\\formatters\\garmin\\WebService::call(Object(okapi\\core\\Request\\OkapiInternalRequest))\n
#3 /srv/ocpl/okapi/core/OkapiServiceRunner.php(139): call_user_func(Array, Object(okapi\\core\\Reque
st\\OkapiInternalRequest))\n#4 /srv/ocpl/okapi/Facade.php(66): okapi\\core\\OkapiServiceRunner::call
('services/caches...', Object(okapi\\core\\Request\\OkapiInternalRequest))\n#5 /srv/ocpl/lib/search.
zip.inc.php(12): okapi\\Facade::service_call('services/caches...', 118284, Array)\n#6 /srv/ocpl/lib/
search.okapi.inc.php(181): call_okapi(Array, 'OP8WWE', 'pl', 'OP8WWE', 0)\n#7 /sr...\n', referer: ht
tps://opencaching.pl//viewcache.php?wp=OP8WWE
```

**Comment by following5** [comment]
Readable version:

```
[Fri Nov 02 19:58:33.489866 2018]
[proxy_fcgi:error] [pid 1344:tid 140579459688192] [client 78.154.8
5.165:55877]
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /srv/ocpl/okapi/services/caches/formatters/garmin/WebService.php:107

Stack trace:
#0 [internal function]: okapi\\core\\OkapiErrorHandler::handle(2, 'count(): Parame...', '/srv/ocpl/okapi...', 107, Array)
#1 /srv/ocpl/okapi/services/caches/formatters/garmin/WebService.php(107): count(NULL)
#2 [internal function]: okapi\\services\\caches\\formatters\\garmin\\WebService::call(Object(okapi\\core\\Request\\OkapiInternalRequest))
#3 /srv/ocpl/okapi/core/OkapiServiceRunner.php(139): call_user_func(Array,Object(okapi\\core\\Request\\OkapiInternalRequest))
#4 /srv/ocpl/okapi/Facade.php(66): okapi\\core\\OkapiServiceRunner::call('services/caches...', Object(okapi\\core\\Request\\OkapiInternalRequest))
#5 /srv/ocpl/lib/search.zip.inc.php(12): okapi\\Facade::service_call('services/caches...', 118284, Array)
#6 /srv/ocpl/lib/search.okapi.inc.php(181): call_okapi(Array, 'OP8WWE', 'pl', 'OP8WWE',0)
#7 /sr...\n', referer: https://opencaching.pl//viewcache.php?wp=OP8WWE
```

**Comment by deg-pl** [comment]
Can we better handle this error exception?

**Comment by following5** [comment]
Sure, it's an OKAPI bug and I will fix it. Looks like older PHP versions did not detect this problem.

**Comment by deg-pl** [comment]
Thanks!

**Comment by teiling88** [comment]
> Looks like older PHP versions did not detect this problem.

@following5 https://3v4l.org/LVRs7 this behaviour changed with php 7.2
