### ISSUE TITLE
Facade::disable_error_handling() should also restore exception handler

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#575]
... otherwise Okapi will handle exceptions in non-Okapi-Code and send emails to Okapi developers.

**Comment by following5** [comment]
Another errorhandler issue: There is a handler recursion on Exceptions in the Settings class (e.g. access to undefined variable in okapi_settings.php).

OCPL now has clean error handling comparable to Okapi, so at least the code comments on that can be removed. Only difference is that @ suppression of error messages is allowed at OCPL (see https://github.com/opencaching/opencaching-pl/commit/270962f55ca47051f8c31c957e2b45483d228344). We could copy that to Okapi, so the error handling would be equivalent. (For OCDE it currently doesn't matter, because it does not use Facade, except for running update).

**Comment by following5** [comment]
Today example of Okapi catching an exception thrown by OCPL code:

```
===== ERROR MESSAGE =====
ErrorException:
file_get_contents(https://geokrety.org/ruchy.php): failed to open stream: HTTP request failed! HTTP/1.0 502 Bad Gateway
=========================

--- Stack trace ---
#0 [internal function]: Utils\Debug\ErrorHandler::handleError(2, 'file_get_conten...', '/srv/ocpl/Contr...', 204, Array)
#1 /srv/ocpl/Controllers/GeoKretyLogController.php(204): file_get_contents('https://geokret...', false, Resource id #356)
#2 /srv/ocpl/Controllers/GeoKretyLogController.php(78): Controllers\GeoKretyLogController->sendLog(Object(lib\Objects\GeoKret\GeoKretLog))
```

**Comment by following5** [comment]
[eeek](https://github.com/opencaching/okapi/blob/681f5997b6e44ce70d2428600de8168bd041c5c8/okapi/core/Exception/OkapiExceptionHandler.php#L134)
