### ISSUE TITLE
OC NL table okapi_diagnostics not found

### ISSUE THREAD

**Issue by following5** [opencaching/okapi#583]
```
===== ERROR MESSAGE =====
okapi\core\Exception\DbException:
SQL Error 1146: Table 'ocnl.okapi_diagnostics' doesn't exist

The query was:

            delete from okapi_diagnostics
            where expires < now()
=========================

--- Stack trace ---
#0 /serve/www/oc_nl/oc/okapi/core/Db.php(206): okapi\core\Db::throwProperDbException(Object(PDOException), '\n            de...')
#1 /serve/www/oc_nl/oc/okapi/core/CronJob/DiagnosticsCleanerJob.php(17): okapi\core\Db::execute('\n            de...')
#2 /serve/www/oc_nl/oc/okapi/core/CronJob/CronJobController.php(80): okapi\core\CronJob\DiagnosticsCleanerJob->execute()
```

The table exists. No idea why this delete throws an error.

**Comment by following5** [comment]
@harrieklomp 
Could you have a look onto the database and check if you can access the table `okapi_diagnostics`? OKAPI says that it does not exists, but MariaDB says it does (on the okapi/devel/dbstruct page).

**Comment by harrieklomp** [comment]
On DEVEL.nl there is no table `okapi_diagnostics`

This error comes from DEVEL.nl site. For now Cronjobs are disabled. Andrixnet will install phpMyAdmin so i can update the DB.

**Comment by following5** [comment]
Okay. OKAPI update should be run, that will create the table. (http://sitename/okapi/update)
